### PR TITLE
Make code cleaner and more understandable

### PR DESCRIPTION
**Pull request by petr7555**
Hi there. I love what you have created. I wanted to help to improve your game as part of a hackathon.

### CODE REVIEW

**Comment by Vertfromage** [comment]
Hey petr7555,

I'm trying to merge pull requests in order of when they arrive if they don't have conflicts. Unfortunately since I merged other pull requests there are conflicts with your branch that need to be resolved, so if you'd like you can resolve the conflicts and I'll merge your pull request next, or I'll get around to resolving conflicts in a day or two when I get a chance.

**Comment by AlexDvorak** [comment]
@petr7555 would you be open to having a Character interface and creating all new characters based off of it (`public class Monster implements CharacterTemplate`) ? instead of keeping all the characters in one file? (I do agree with your changes though as is)

**Comment by petr7555** [comment]
> @petr7555 would you be open to having a Character interface and creating all new characters based off of it (`public class Monster implements CharacterTemplate`) ? instead of keeping all the characters in one file? (I do agree with your changes though as is)

**Comment by petr7555** [comment]
@AlexDvorak I like the idea and I will do it. I would like to merge those changes first, however, and create a new PR for the interface changes.

**Comment by petr7555** [comment]
@Vertfromage I have merged the upstream branch and now it is possible to merge without any problems.

**Pull request merged**
